# Generated by Django 2.2.10 on 2020-05-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_relocate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
