# Generated by Django 2.2.10 on 2020-05-27 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_stops.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('route_numbers', models.ManyToManyField(related_name='stations', through='bus_stops.RouteStation', to='bus_stops.Route')),
            ],
        ),
        migrations.AddField(
            model_name='routestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_stops.Station'),
        ),
    ]
