# Generated by Django 2.2.10 on 2020-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
    ]
